FROM emscripten/emsdk:latest AS core-build

RUN mkdir -p /mpp-cpu
WORKDIR /mpp-cpu

COPY mpp-cpu .

RUN RUNTEST=1 make compile-tests
RUN make run-tests

RUN make clean # clean because compiled to export will be on another format

RUN make
