/*
 * File: /src/lib/constants.h
 * Project: mpp-cpu
 * File Created: Monday, 21st March 2022 11:08:39 am
 * Author: https://github.com/nullxx (mail@nullx.me)
 * -----
 * Last Modified: Sunday, 10th April 2022 4:03:18 pm
 * Modified By: https://github.com/nullxx (mail@nullx.me)
 */

#ifndef constants_h
#define constants_h

#define MEM_VALUE_SIZE_BITS 8
#define MEM_SIZE_KB 64
#define MEM_START_VALUE 0x00

#define DATA_BUS_SIZE_BITS 8
#define DIR_BUS_SIZE_BITS 16

#define ID_LOAD_BIT_SIZE_BITS 2
#define SELALU_LOAD_BIT_SIZE_BITS 3
#define SELREG_LOAD_BIT_SIZE_BITS 2
#define REGCAR_LOAD_BIT_SIZE_BITS 2
#define SELDIR_LOAD_BIT_SIZE_BITS 2

#define SP_REG_SIZE_BIT 16
#define PCH_REG_SIZE_BIT 8
#define PCL_REG_SIZE_BIT 8
#define PC_REG_SIZE_BIT 16
#define H_REG_SIZE_BIT 8
#define L_REG_SIZE_BIT 8
#define ACUMM_REG_SIZE_BIT 8
#define OP2_REG_SIZE_BIT 8
#define REG_SIZE_BIT 8  // A, B, C, D
#define FLAG_REG_SIZE_BIT 1
#define RI_REG_SIZE_BIT 8

#define FLAGSINTA_BUS_SIZE_BITS 8
#define FLAGSINTA_FC_BUS_BIT_POSITION 0
#define FLAGSINTA_FZ_BUS_BIT_POSITION_SOURCE 1
#define FLAGSINTA_FZ_BUS_BIT_POSITION_TARGET 7
#define FLAGSINTA_GND_START_BIT_POSITION 1
#define FLAGSINTA_GND_END_BIT_POSITION 5
#define FLAGSINTA_INTA_BUS_BIT_POSITION 6
#define FLAGSINTA_GND_CHAR_VALUE 0

#define MAX_CALC_BIN_SIZE_BITS 16

#define ALU_MEM_RELATION 2 * 1 // factorial(2)
#define ACUM_FLAGS_RELATION 2 * 1 // factorial(2)

#define CONTROL_BUS_EOI_BIT_POSITION 0
#define CONTROL_BUS_INTAIN_BIT_POSITION 1
#define CONTROL_BUS_SPCAR_BIT_POSITION 2
#define CONTROL_BUS_PCLCAR_BIT_POSITION 3
#define CONTROL_BUS_PCHCAR_BIT_POSITION 4
#define CONTROL_BUS_LCAR_BIT_POSITION 5
#define CONTROL_BUS_HCAR_BIT_POSITION 6
#define CONTROL_BUS_FLCAR_BIT_POSITION 7
#define CONTROL_BUS_SELFL_BIT_POSITION 8
#define CONTROL_BUS_OP2CAR_BIT_POSITION 9
#define CONTROL_BUS_ACCAR_BIT_POSITION 10
#define CONTROL_BUS_REGCAR_BIT_POSITION 11
#define CONTROL_BUS_PCCAR_BIT_POSITION 12
#define CONTROL_BUS_RICAR_BIT_POSITION 13
#define CONTROL_BUS_PCLBUS_BIT_POSITION 14
#define CONTROL_BUS_PCHBUS_BIT_POSITION 15
#define CONTROL_BUS_ALUBUS_BIT_POSITION 16
#define CONTROL_BUS_ACBUS_BIT_POSITION 17
#define CONTROL_BUS_FLBUS_BIT_POSITION 18
#define CONTROL_BUS_MEMBUS_BIT_POSITION 19
#define CONTROL_BUS_REGBUS_BIT_POSITION 20
#define CONTROL_BUS_LE_BIT_POSITION 21
#define CONTROL_BUS_ID_0_BIT_POSITION 22
#define CONTROL_BUS_ID_1_BIT_POSITION 23
#define CONTROL_BUS_SELDIR_0_BIT_POSITION 24
#define CONTROL_BUS_SELDIR_1_BIT_POSITION 25
#define CONTROL_BUS_MXREG_0_BIT_POSITION 26
#define CONTROL_BUS_MXREG_1_BIT_POSITION 27
#define CONTROL_BUS_SELALU_0_BIT_POSITION 28
#define CONTROL_BUS_SELALU_1_BIT_POSITION 29
#define CONTROL_BUS_SELALU_2_BIT_POSITION 30
#endif /* constants_h */
